server:
  image: nginx:1.9
  volumes:
    - static:/usr/local/static
    - nginx:/etc/nginx/conf.d
  ports:
    - "8000:80"
  links:
    - app
app:
  build: app
  volumes:
    - app:/usr/src/app
  links:
    - db
db:
  image: postgres:9.4
  volumes:
    - postgres:/var/lib/postgresql/my
