dbdata:
  image: postgres:9.4
  command: true
dbbackup:
  image: busybox
  volumes_from:
    - dbdata
  command: true
db:
  build: postgres
  volumes_from:
    - dbdata
webapp:
  build: webapp
  volumes:
    - webapp:/usr/src/webapp
  links:
    - db
server:
  image: nginx:1.9
  volumes:
    - static:/usr/local/static
    - nginx:/etc/nginx/conf.d
  ports:
    - "8000:80"
  links:
    - webapp
